name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Install ngrok
      run: npm install ngrok -g

    - name: Start server & ngrok tunnel
      run: |
        npm start &
        sleep 10
        ngrok http 8080 &
        sleep 10
    - name: Get ngrok public URL
      run: |
        curl http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

